### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0

### ISSUE THREAD

**Issue by hellowuxin** [CasterWx/python-girlfriend-mood#4]
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    initMoonValue()
  File "run.py", line 16, in initMoonValue
    word = f.readlines()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 23: invalid start byte

MoodValue.txt的编码应该不是‘utf-8’？

**Comment by hellowuxin** [comment]
gbk打开了
